eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


security:
  users:
    - username: user1
      password: password1
      roles: ADMIN
    - username: user2
      password: password1
      roles: USER
    - username: user3
      password: password1
      roles: USER

logging:
  level:
    root: INFO
